Fallback to building a Restforce::Mash if the attributes hash does not contain a type
When trying to make arbitrary API calls to, for example, the
/ui-api/object-info/<object>/picklist-values/ endpoint, the response
contains an attributes key but no type key, which was causing the following:

NoMethodError: undefined method `[]' for nil:NilClass
from .../restforce-4.2.1/lib/restforce/mash.rb:32:in `klass'

This ensures that there is a type key inside of the attributes hash,
otherwise it just falls back to Restforce::Mash